copy zip file to dist directory

diff --git a/build/mkjs9app b/build/mkjs9app
--- a/build/mkjs9app
+++ b/build/mkjs9app
@@ -1,11 +1,15 @@
 #!/bin/bash
 # set -x
 
+NAME="js9"
 CDIR=`pwd`
 SRCDIR=$CDIR/src
+DISTDIR=$CDIR/dist
 ANALYSIS_PACKAGES="funtools regions"
 NPM_PACKAGES="@electron-forge/maker-pkg"
 OSID=`node -e 'console.log(\`${os.platform()}-${os.arch()}\`)'`
+OSP=`echo $OSID | awk -F- '{print $1}'`
+OSA=`echo $OSID | awk -F- '{print $2}'`
 if [ x"$OSID" = xdarwin-x64 ]; then
   SSID=`/System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport -I | egrep ' SSID:' | awk '{print $2}'`
 fi
@@ -74,12 +78,13 @@ while [ x"$1" != x ]; do
     esac
 done
 
-printf "\nBuilding JS9 App: $OSID $SSID `date` ...\n"
+printf "\nBuilding $NAME app: $OSID $SSID `date` ...\n"
 
 # initialize src directory?
 if [ x"$INIT" = xtrue ]; then
   printf "\ncreating new $SRCDIR directory\n"
   rm -rf $SRCDIR && mkdir -p $SRCDIR || error "can't init $SRCDIR"
+  mkdir -p $DISTDIR || error "can't init $DISTDIR"
 fi
 
 # initialize app using electron-forge
@@ -152,4 +157,7 @@ if [ x"$DIST" = xtrue ]; then
   cd $SRCDIR || error "can't enter $SRCDIR directory"
   # npm run package
   npm run make
+  # copy zip file
+  cd $DISTDIR || error "can't enter $DISTDIR directory"
+  cp -p $SRCDIR/out/make/zip/$OSP/$OSA/${NAME}-${OSID}-${VER}.zip .
 fi
